### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by spit4520** [psas/gps-rf-board#7]
Hi,

I am trying to learn about how to build my own GPS receiver, and I am also trying to learn how to emulate signals directly for testing. I want to be able to inject signals manually over the SMA connector from another device in order to "replay" a scenario, do you have any research you could point me towards?

Thanks

**Comment by andrewgreenberg** [comment]
Hi!
Nope, this particular project is no longer active. We've upgraded it for use in a CubeSat, please see <https://github.com/oresat/oresat-gps-hardware>.  

Emulating GPS signals for testing is hard but possible; see GNU Radio GPS toolkits, and the various Python-based toolkits for GPS. There are commercial systems (see Spirent) for this sort of thing, but they're usually expensive. Sorry we can't help out more!
